application: smsandvoice
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled


handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(.*)

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /_ah/queue/deferred
  script: main.py
  login: admin

- url: /(.*\.(gif|png|jpg|js|css|html))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|js|css|html))

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js
  
- url: /google73a6e106114591c7.html
  static_dir: static

- url: /.*
  script: main.py
